name: easy_recycle_flutter
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: 0.20.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  geolocator: ^11.0.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/arb/app_de.arb
    - lib/l10n/arb/app_tr.arb
    - lib/l10n/arb/app_en.arb
    - assets/logo/
    - assets/images/
    - assets/uix/
    - assets/fonts/
    - assets/easy_recycle_images/
    - assets/Easy Recycle Images/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/app_logo_light_1024.png
  remove_alpha_ios: true
  adaptive_icon_foreground: assets/logo/ic_launcher_foreground_432.png
  adaptive_icon_background: "#F7FAFF"
